name: obsr
version: v1.0.1
summary:   peer-to-peer network based digital currency
description: |
  Obsr is a free open source peer-to-peer electronic cash system that
  is completely decentralized, without the need for a central server or
  trusted parties.  Users hold the crypto keys to their own money and
  transact directly with each other, with the help of a P2P network to
  check for double-spending.

grade: stable
confinement: strict

apps:
  daemon:
    command: obsrd
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
    aliases: [obsrd]
  qt:
    command: desktop-launch obsr-qt
    plugs: [network, network-bind, unity7]
    aliases: [obsr-qt]
    desktop: obsr.desktop
  cli:
    command: obsr-cli
    aliases: [obsrd-cli]

parts:
  obsr:
    source: https://github.com/observernet/obsr
    source-type: git
    source-tag: v1.0.1
    plugin: autotools
    # XXX We don't want to copy the full blockchain every time that the snap is
    # updated, but there's no way to define a default data dir in bitcoin-qt.
    # Also, it would be better if we could split the wallet from the blockchain
    override-build: git apply $SNAPCRAFT_STAGE/default_data_dir.patch
    build-packages:
      - g++
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      # Optional.
      - libqrencode-dev
    stage-packages: [ca-certificates]
    after:
      - berkeleydb
      - desktop-qt5
      - patches
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all

  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    override-build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
    override-build: |
      cd build_unix
      make install
    prime:
      - -*
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/gui
    plugin: dump
